///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Car {
/*
{
  "_id": "61550157557a3030c8b19119",
  "name": "Camry 2022",
  "subname": "Cure for the common commute",
  "url360": "https://msnautosblob.akamaized.net/izmo-prod/izmo360/en-us/2019/toyota/camry/ext360/angle",
  "createdAt": "2021-09-30T00:14:15.694Z",
  "updatedAt": "2021-09-30T00:21:27.852Z",
  "price": 89000,
  "id": "61550157557a3030c8b19119"
} 
*/

  String? Id;
  String? name;
  String? subname;
  String? url360;
  String? createdAt;
  String? updatedAt;
  int? price;
  String? id;

  Car({
    this.Id,
    this.name,
    this.subname,
    this.url360,
    this.createdAt,
    this.updatedAt,
    this.price,
    this.id,
  });
  Car.fromJson(Map<String, dynamic> json) {
    Id = json["_id"]?.toString();
    name = json["name"]?.toString();
    subname = json["subname"]?.toString();
    url360 = json["url360"]?.toString();
    createdAt = json["createdAt"]?.toString();
    updatedAt = json["updatedAt"]?.toString();
    price = json["price"]?.toInt();
    id = json["id"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["_id"] = Id;
    data["name"] = name;
    data["subname"] = subname;
    data["url360"] = url360;
    data["createdAt"] = createdAt;
    data["updatedAt"] = updatedAt;
    data["price"] = price;
    data["id"] = id;
    return data;
  }
}
